In [20]:
#Question 1

import numpy as np
ar=np.random.rand(10,1)
print(ar)
print(ar.shape)
print('Mean:',ar.mean())




[[0.89791093]
 [0.46001539]
 [0.31539322]
 [0.67016322]
 [0.94549207]
 [0.46411799]
 [0.86307448]
 [0.03340622]
 [0.96923644]
 [0.21801517]]
(10, 1)
0.5836825132005738


In [18]:
#Question 2

import numpy as np
import math
ar=np.random.rand(20,1)
print(ar)
print('standard deviation:',ar.std())
print('variance:',ar.std()**2)

[[0.15795258]
 [0.5836987 ]
 [0.60749751]
 [0.23883226]
 [0.24181109]
 [0.40011821]
 [0.94762821]
 [0.74138748]
 [0.67471218]
 [0.01996741]
 [0.10906252]
 [0.0100931 ]
 [0.28340118]
 [0.6836305 ]
 [0.43532791]
 [0.68594559]
 [0.94689537]
 [0.64198881]
 [0.39090634]
 [0.57369517]]
standard deviation: 0.27657570689436356
variance: 0.0764941216441169


In [26]:
#Question 3

a=np.random.rand(10,20)
b=np.random.rand(20,25)
c=np.matmul(a,b)
print(np.sum(c))


1267.2730511520172


In [41]:
#Question 4

a=np.random.rand(10,1)
print(a)
print("*"*20)
def fun(a):
     return 1/(1+np.exp(-a))
for i in range(10):
    print(fun(a[i]))

[[0.50417644]
 [0.99629862]
 [0.33390865]
 [0.93691958]
 [0.65645258]
 [0.64149236]
 [0.06835348]
 [0.77125483]
 [0.46933509]
 [0.29450245]]
********************
[0.62344031]
[0.73033022]
[0.58271011]
[0.71847701]
[0.65846306]
[0.65509073]
[0.51708172]
[0.68379228]
[0.61522637]
[0.57309805]
